#################################################################
######  Copyright: Regents of the University of Minnesota  ######
#################################################################

TARGET_PATH = Sys.getenv('TARGET_PATH')
source(file.path(TARGET_PATH, 'lib', 'cosine.r'))

# For future reference, this computes distances between the rows of the input matrix

# NOTE: this function assumes that NaN values in cos_sim are generated by zero length
# vectors. It replaces them with 0 in the distance matrix, so that these blank rows/
# columns will cluster together.
cos_dist_for_clust <- function(mat, ...) {

    dists <- 1 - cos_sim(t(mat), t(mat), ...)
    dists[is.nan(dists)] <- 0
    dists[is.na(dists)] <- 0

    as.dist(dists)
}




